### ISSUE TITLE
item err

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#14]
There is a problem, which has existed from version 22 to version 24, but the chance of random appearance is very small, and the attributes of the items on the body will become infinite, such as the required strength, agility, level, intelligence, weapon skills that should not appear, and sometimes the items picked up will also prompt illegal copying of items
pic url:https://yaoge.me/err.png
https://yaoge.me/err1.jpg
https://yaoge.me/err2.png
https://yaoge.me/err3.jpg

**Comment by yao123ge** [comment]
I'm not sure if it's because of the loss of durability

**Comment by nicomuratona** [comment]
Did you modified ItemOption.txt file?

**Comment by yao123ge** [comment]
I didn't change the ItemOption file, this error is a random case that was found while fixing equipment durability. After picking up some dropped items and moving them to the backpack, the mouse will indicate that the item is a duplicate item and then disconnect

**Comment by nicomuratona** [comment]
What do you mean with "fixing equipment durability"? The durability of each item is directly copied from webzen's item. The maximum of durability is 255. Did you overpass that maximum?

**Comment by yao123ge** [comment]
Weapons and equipment will slowly decrease in durability while they are in use, and then they can be repaired by the blacksmith or the "hammer" icon in the lower left corner of the backpack

**Comment by nicomuratona** [comment]
mmm it seems like a bad config of items. Did you look into the DataServer if it drops an error log? Because the "duplicated item" is from the database giving an existant serial.
Your problems is too generic to discover where is the problem. I assume is something you changed in the configs because never happened in the default files from this github.

**Comment by yao123ge** [comment]
item's required attributes suddenly become high.,And the problem of copying items.,It's not very serious.,It's only occasional.,I can't say what the reason is.,If you can't fix it.,Re-log in to the game once.,Or empty the backpack once can be solved.

**Comment by nicomuratona** [comment]
The problem is not that i cannot fix it, its that i cannot test it. I've never generated that error, that's why i'm saying that your error is something you generated in your configs because no one has reported me that yet. If you use the files default as they are in this github and still have the problem, then i can test it and check how to fix it but that doesn't happen.
If you discover how to generate the error, i can fix the error because i can try it by myself and test the fix but i don't know how to generate that error.
