### ISSUE TITLE
angel bug

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#29]
![长图_1733313048207](https://github.com/user-attachments/assets/677e4c8e-0ed7-49d1-ab7d-4c388a4781f2)

**Comment by yao123ge** [comment]
When using an exc item, the item has an increase of Max HP +4%, but there is no change in maxlife

**Comment by nicomuratona** [comment]
Those are just visual stats that are not reflected because they are calculated by main.exe instead of being received by the gameserver.
When calculating damage, those stats will be considered by the gameserver, processing the corresponding defense or additional damage.

I will try to somehow synchronize those stats by receiving them from the gameserver and reflecting them in that interface although I don't have much time to do it, unfortunately.
