### ISSUE TITLE
lucky number

### ISSUE THREAD

**Issue by yao123ge** [nicomuratona/MuEmu-0.97k-kayito#9]
Thanks to the author for the update all the time,In the latest version,I found,Coding problems、Pet store problems、MG profession use Rune Blade weapon problems have been solved,But there are still a few problems,When using the game locally, the ping value is still kept at 46,47ms,lucky number can't be displayed,It's always 000-000-000.In addition, do you consider adding Auto Pick and AutoAttack functions, I see that these two features have been added in the version of CUSTOM by Siniestro, which really allows players to spend less time staring at the screen and picking up items
Thanks again to the author for his hard work

**Comment by nicomuratona** [comment]
The ping is a simple system that sends a packet and saves the timestamp, then when it gets the response substracts the timestamp of that packet and that difference is the ping in miliseconds. I don't really know why is taking 47 ms in a local send/receive lapse.

The lucky number won't be displayed because it works differently. Heres is a video explaining how to use it: https://youtu.be/-6-aC5sK_hs?feature=shared
This is because Webzen originally used the Lucky Number with payment receipts. The user registered the Lucky Number that appeared on their receipt and then, on a certain date, a lottery was held with all the Lucky Numbers that had been generated to win a prize.
I needed to make the Lucky Number system independent of payment receipts so that anyone can use it, even if they have no sales or do not provide payment receipts. That's why it is programmed differently and works as seen in the video.

Auto Pick and Auto Attack won't be added because I don't support to automate the game and promote ghost servers with no players playing, only afks. Anyway you have the source code to add it by yourself or to pay a coder to do it.
